# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-cluster-ip-service
# spec:
#   type: ClusterIP
#   selector:
#     component: mongo
#   ports:
#     - protocol: TCP   #to be decided later
#       port: 27017
#       targetPort: 27017  

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: microapp
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
