apiVersion: v1
kind: Service
metadata:
  name: appointments-service
  namespace: microapp
spec:
  selector:
    app: appointments-service
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
