name: Build and Deploy Multi-Service

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push each service
      - name: Build and push service-api
        uses: docker/build-push-action@v6
        with:
          context: ./appointments_service
          file: ./appointments_service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/appointments_service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/appointments_service:${{ github.sha }}

      - name: Build and push service-worker
        uses: docker/build-push-action@v6
        with:
          context: ./express
          file: ./express/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/express:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/express:${{ github.sha }}

      - name: Build and push service-frontend
        uses: docker/build-push-action@v6
        with:
          context: ./login_page
          file: ./login_page/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/login_page:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/login_page:${{ github.sha }}

  refresh-local-k8s:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Refresh local Kubernetes deployments
        run: |
          echo " Refreshing Kubernetes deployments..."
          kubectl set image deployment/api-deployment api-container=${{ secrets.DOCKERHUB_USERNAME }}/service-api:latest
          kubectl set image deployment/worker-deployment worker-container=${{ secrets.DOCKERHUB_USERNAME }}/service-worker:latest
          kubectl set image deployment/frontend-deployment frontend-container=${{ secrets.DOCKERHUB_USERNAME }}/service-frontend:latest
          
          echo " Rolling out updates..."
          kubectl rollout restart deployment/api-deployment
          kubectl rollout restart deployment/worker-deployment
          kubectl rollout restart deployment/frontend-deployment
          
          echo "âœ… Checking rollout status..."
          kubectl rollout status deployment/api-deployment
          kubectl rollout status deployment/worker-deployment
          kubectl rollout status deployment/frontend-deployment